TAG: jilong:spider2:dnm_location:DUM:workflowconfiguration
account: spider2
project_name: DNM Location Analysis - DUM
project_id: DUM
species_prefix: dum
x_chromosomes:
  - dum_X1
  - dum_X2
working_directory_path: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/science_resub/DNM_location
output_directory_path: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/science_resub/DNM_location/steps
log_directory_path: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/science_resub/DNM_location/logs
scripts_path: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/science_resub/DNM_location/dnm_distribution/workflow_sources
callable_genome_dir: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/science_resub/DNM_location/data/DUM/callable_genome
callable_summary_file: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/steps/germline/minDP/DUM/callable/minDP_26/DUM_callable_minDP26.tsv
dnm_file: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/science_resub/DNM_location/data/DUM/dnm/DUM_minDP_26_automate_classified.tsv
genome_fai: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/science_resub/DNM_location/data/DUM/genome/DUM_ncbi_chromosome.fa.fai
window_size: 25000000
