TAG: jilong:spider2:dnm_location:MIM:workflowconfiguration
account: spider2
project_name: DNM Location Analysis - MIM
project_id: MIM
species_prefix: mim
x_chromosomes:
  - mim_X1
  - mim_X2
working_directory_path: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/science_resub/DNM_location
output_directory_path: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/science_resub/DNM_location/steps
log_directory_path: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/science_resub/DNM_location/logs
scripts_path: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/science_resub/DNM_location/dnm_distribution/workflow_sources
callable_genome_dir: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/science_resub/DNM_location/data/MIM/callable_genome
callable_summary_file: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/steps/germline/minDP/MIM/callable/minDP_26/MIM_callable_minDP26.tsv
dnm_file: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/science_resub/DNM_location/data/MIM/dnm/MIM_minDP_26_automate_classified.tsv
genome_fai: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/science_resub/DNM_location/data/MIM/genome/MIM_ncbi_chromosome.fa.fai
window_size: 25000000
