# Tag identifying file association.
TAG: jilong:spider2:checking_variant_in_genes:workflowconfiguration
# The name of the relevant project account.
account: spider2
# Name of species being analyzed
species_name: Stegodyphus bicolor
# ID of species for short
species_id : BIC

  
# old genome reference:
old_ref: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/data/hyper/BI_hifi_hic_scaffolded_trim.fa
# new genome reference:
new_ref: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/data/hyper/BI_ncbi_chromosome.fa
# old gene gffs:
gene:
  - MLH1
  - PMS2
  - MBD4
  - MUTYH
  - OGG1
  - TDG
  - MSH2
  - MSH6
  - ERCC2
# random genes
random_gene:
  - CHD7
  - MIGA
  - DEN6A
  - 5HT2B
  - KAPC3
  - TBC15
  - ERC2
  - MTEF3
  - RIBC2
  - BRAP
  - SRP19
  - BHE22
  - ACOD1
  - GLRX5
  - GALK1
  - SKEL1
  - PLPL7
  - PGTB2
  - LUC7L
  - CAPAM
  - IQEC1
  - CTR4
  - SC6A4
  - SCHI1
  - ACH3
  - MSH5
  - AL8A1
  - TRM2A
  - GSHB
  - ZASP
  - DNLI3
  - KIME
  - VA0D1
  - VPS39
  - BRD8
  - EGLN2
  - ICCR
  - DAAF5
  - DHGL
  - MIB1
  - TM181
  - IFT57
  - GRAP1
  - ARMC9
  - AMMR1
  - CDK5
  - TDIF1
  - SC24C
  - HHATL
  - RMND1
  - PGBD3
  - RAB21
  - RN157
  - H2AV
  - CLCN2
  - FMO5
  - HEM4
  - STNB
  - POL2
  - BIG1
  - ELOA1
  - MKRN3
  - TM7S3
  - KCTD9
  - STK11
  - GSTM1
  - NAC3
  - TINC
  - R3HCL
  - CAN5
  - PDE4C
  - TOLL8
  - SVEP1
  - MA2A2
  - FOXO4
  - KDM6B
  - SYAP1
  - BAIP3
  - ADRL
  - DEOC
  - TM9S4
  - MKROS
  - G6PT3
  - RBL2A
  - HNRL1
  - OSGI1
  - TBCK
  - CCNA1
  - ACADV
  - MLX
  - ASPG
  - UBC10
  - GPAT1
  - TM131
  - APKC
  - PDE1
  - UBC2M
  - MAS
  - UQCC1
  - CSAD
  - NEP
  - RGMA
  - TDPZ5
  - FRL
  - IDH3A
  - CP4V2
  - IQGA1
  - RDX
  - RUSD2
  - EPN4
  - HCN4
  - HINT1
  - ATX1L
  - GT2D2
  - TBL1R
  - ZBED5
  - DEN2C
  - KDSR
  - AP1S2
  - PPIL2
  - GPRK1
  - OBSTE
  - MAPK2
  - PAQRA
  - ZMYM6
  - RRP1B
  - NOMO3
  - FRAS1
  - P20D2
  - TIGD7
  - RFT1
  - SNUT2
  - UBE2H
  - KCC2A
  - AVL9
  - PNCB
  - SYAC
  - UBR4
  - BND7A
  - TR112
  - JERKY
  - THOC1
  - PNUT
  - BEST3
  - ATPK
  - UTP20
  - SV2C
  - CP1B1
  - BTBD6
  - DHTK1
  - N6MT1
  - GNA1
  - S22AF
  - TM9S1
  - SMCA5
  - SL9A7
  - DEN1A
  - APC7
  - USE1
  - COR2A
  - NMDE4
  - AREL1
  - AP2C
  - FGL2
  - UB2Q2
  - DOS
  - PUR4
  - SYPM
  - NMDE1
  - AP1M1
  - SDA1
  - T2FA
  - ANKF1
  - MTHFS
  - QCR8
  - MBIP1
  - DACH2
  - MDN1
  - NBEA
  - WDR76
  - PCNA
  - NDUS3
  - BAB2
  - NXT1
  - MTF1
  - CRK
  - THOP1
  - LANC3
  - SI1L1
  - EXD2
  - ODBA
  - FBX30
  - MEF2B
  - SC6A7
  - JNK
  - SIM2
  - SY14L
  - RYR
  - DCST2
  - ANGE2
  - FABD
  - FKRP
  - ZMAT2
  - GYS
  - PRP4B
  - TBCC
  - DCXR
  - AT2B3
  - HARS1
  - CANB2
  - TINAL
  - DMPK
  - CSKI1
  - GSC
  - ORC4
  - REXO5
  - FA43A
  - PCCA
  - 2A5G
  - SAN
  - LASP1
  - MADD
  - XPO5
  - PLDX1
  - SAE1
  - NUDC1
  - BET1
  - EFHC1
  - WDR46
  - MFS11
  - MCAF1
  - KCMF1
  - TYSY
  - SPB3
  - MRP7
  - CNOT1
  - SF3A2
  - PH4H
  - NELFB
  - HUTI
  - DISP1
  - COMD9
  - ATAD2
  - CEP20
  - ALKMO
  - OTU7B
  - ADPGK
  - WDR3
  - VPS54
  - EXO1
  - SNX12
  - PHIP
  - COQ4
  - RPF2
  - MCLN1
  - RBX2
  - TPC
  - NKAI2
  - HTS
  - UN112
  - ASND1
  - B3GNL
  - CERS6
  - CSMD1
  - UBP7
  - MET7B
  - PTPRQ
  - DUS14
  - GRIK2
  - SIK3
  - SCFD1
  - MRE11
  - SPTC2
  - HS3SA
  - VACHT
  - PSAL
  - FAAH2
  - NUDT9
  - FA20C
  - PUM3
  - DHDDS
  - TONSL
  - LOLAL
  - SIK2
  - ATG5
  - PLPL9
  - S29A3
  - TMTC1
  - RTXE
  - NUD15
  - FACE1
  - DPOE4
  - NBAS
  - AT8B2
  - HUS1
  - BRDT
  - RTJK
  - NAT10
  - VNNL2
  - ZDH14
  - SNR40
  - RPR1B
  - CHD4
  - PRS30
  - TAGAP
  - SCYL1
  - EAF2
  - TGBR3
  - RHOU
  - STX8
  - DGKE
  - DHYS
  - CANB
  - A1CF
  - EXOS7
  - AQR
  - HGD
  - RTBS
  - EXOS3
  - SCAI
  - CLASR
  - DCPS
  - SYYC
  - K1586
  - ABCG8
  - ENOX2
  - RRP7A
  - ZFPL1
  - TSN14
  - DPS1
  - CEBPZ
  - PP4RL
  - PI42A
  - CACP
  - ATX3
  - TMOD2
  - SO4A1
  - SANBR
  - SLC31
  - GPCP1
  - REG2
  - NRDE2
  - DTWD1
  - SARDH
  - TYW5
  - KCNAW
  - RL37A
  - MA2A1
  - ZN618
  - SELN
  - INSI2
  - PIP30
  - MAD
  - AMOT
  - MY18A
  - COPZ1
  - VAT1L
  - NPAS3
  - COG8
  - CHIT2
  - SPF45
  - RT29
  - C1GLT
  - RASF8
  - COMDA
  - GOG7B
  - ODBB
  - OTU7A
  - PDES1
  - CONT
  - ZCRB1
  - INT9
  - STK16
  - NDUA8
  - ISCA1
  - ZNRF2
  - UBQL1
  - ZMAT5
  - RBM22
  - PGPI
  - STOX1
  - MDGA1
  - DDX47
  - PICO
  - EAA2
  - CGAT1
  - EHMT1
  - PAPOB
  - RUVB2
  - WUN
  - GFRP
  - DDX31
  - SWET1
  - BTG3
  - CDK9
  - FMO2
  - LIPR3
  - ECI3
  - CDC20
  - NUMB
  - GOSR1
  - CRIP1
  - AUTS2
  - NCAH
  - HEM6
  - KIF12
  - SPSB3
  - AG10B
  - NEB2
  - PACER
  - ZPR1
  - 4ET
  - DDX41
  - PSMF1
  - GDC
  - RALA
  - RPC8
  - RM49
  - WDR44
  - TRAP1
  - CTNA
  - CC14B
  - PLGT2
  - WASF3
  - CK5P1
  - DYH14
  - SC5A2
  - MOT12
  - MKS1
  - PYRG1
  - HAP40
  - CREBB
  - HEM3
  - P2R3A
  - VP37B
  - FANCM
  - TPPC4
  - APOD
  - NOC2L
  - RHBL2
  - FRMD7
  - CRFR2
  - ALG3
  - ARL4C
  - SUMF1
  - GAS1
  - PLOD
  - PDFR
  - SNP25
  - UBA5
  - I2BP2
  - UAP1
  - AP3B1
  - ATLA2
  - MOCS1
  - ECE2
  - INO80
  - RL14
  - RHG32
  - TAF8
  - PPM1E
  - STX5
  - NUD22
  - OFUT2
  - RETR3
  - AQP9
  - CTR9
  - THIOM
  - INPP
  - TPPC8
  - MILK2
  - NPAS4
  - SOX
  - PCSK7
  - XPO1
  - DPYL3
  - NHP2
  - CA2D2
  - PAR6G
  - SMS1
  - UTP18
  - ZCH24
  - PNR
  - PRP39
  - SUV3
  - RB27A
  - RDH13
  - PTPRO
  - SPP2B
  - ZMIZ1
  - TBD
  - RB27C
  - B3GT6
  - DDB1
  - CAD87
  - TP4AP
  - CBPC4
  - ROS1
  - DERL2
  - TGFR1
  - SMAP2
  - BCL9
  - CDKL1
  - KIF11
  - SPTB1
  - EMC5
  - CASPA
  - RBP1
  - FAT2
  - TACC3
  - M3K15
  - STIM
  - DPYS
  - PDCD4
  - SGK2
  - TRUB2
  - ANO10
  - NAGAB
  - KLHL1
  - CNIH4
  - FPPS
  - PI51C
  - ZMYM5
  - HS12A
  - MAD1
  - GP156
  - NP1L1
  - TMTC2
  - TTBK2
  - NOX4
  - MOT3
  - HDC
  - WDR7
  - KAPC1
  - SYTL5
  - MLP3B
  - SGCG
  - DEK
  - A16L1
  - GRCR1
  - NIPA3
  - NAPEP
  - CAS
  - AP3D1
  - GTPB8
  - EDEM2
  - HHEX
  - CUL4A
  - DUS4L
  - ZN207
  - EPG5
  - UBP36
  - RHBT2
  - FUZZY
  - HCFC2
  - ARL5B
  - MMP21
  - FNTA
  - BSCL2
  - ANXB9
  - BUP1
  - CHSTB
  - DLISH
  - BDGED
  - KT3K
  - DESI1
  - MNX1
  - GABR2
  - ESS2
  - IRX5
  - ABCG4
  - RB3GP
  - TSN8
  - KGUA
  - PTPRN
  - HFM1
  - INT2
  - KCJ12
  - BBS7
  - FIS1
  - MGT4D
  - SCAF8
  - B4GT7
  - PGRP1
  - ALG12
  - COQ6
  - PGRP2
  - S2611
  - MTX2
  - UBR7
  - THOC7
  - KCD20
  - APC11
  - RO60
  - CERK1
  - KCTD5
  - SSRB
  - NADK
  - NAGK
  - VRK2
  - PATJ
  - F151B
  - TPC1
  - UBAC2
  - NU214
  - NEMP1
  - HID1
  - TAB1
  - APBP2
  - VAMP7
  - ATPF2
  - GOGA4
  - ZN608
  - PKHM3
  - TPX2
  - ZC12C
  - RNH2A
  - SMO
  - RT11
  - EXOC2
  - T2EA
  - MY31D
  - HYPK
  - NPRL3
  - FER3L
  - TX264
  - LSM7
  - UBP3
  - PRS6A
  - GBRR2
  - ACHA2
  - ATX2
  - ROUGH
  - MTRR
  - TSN6
  - CC148
  - ANO8
  - COG1
  - JKAMP
  - NSA2
  - TMCC2
  - NKAP
  - TXN4A
  - ALG5
  - UCP5
  - C12A5
  - CBPC6
  - RLA1
  - CYH1
  - MPI
  - DHX8
  - PGM5
  - PDK
  - TSN4
  - BAG2
  - XPO6
  - ATTY
  - ROP
  - DHRS7
  - RAB10
  - ACSL1
  - DDX4
  - RM09
  - CLPP
  - ICA
  - MCTP1
  - GCY3E
  - PROM1
  - ATL5
  - ZSWM5
  - FREM2
  - RHPN1
  - RIOK1
  - CPESY
  - KAD3
  - CYCL
  - TMM18
  - MIRO1
  - GPSM2
  - QTC
  - BMP2K
  - PTPRF
  - STC
  - FAD1
  - VIAAT
  - ACO13
  - RTCB
  - DCOR
  - KRBA2
  - PDE2A
  - MARH3
  - VTA1
  - CE120
  - 2ABA
  - NKX62
  - PAFA
  - WAC2C
  - NDNF
  - CFA43
# vcf file of the species germline mutation rate scanning
species_vcf: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/steps/gatk/genotype/BIC/BIC_GATK.vcf.gz

#Gene identification results
homologs_blast: /faststorage/project/spider2/social_spiders_2020/people/jilong/steps/annotate/gene_identify/DUM/dumicola_eukaryota_match.tsv
#Species used for gene identification
homologs_blast_species: DUM
#gff annotation of the genes in the species for gene identification
homologs_blast_species_gff: /faststorage/project/spider2/social_spiders_2020/people/jilong/steps/annotate/braker/dumicola/etp_mode/DUM_braker.gff3
#gff of the species to find homologs in
target_species_gff: /faststorage/project/spider2/social_spiders_2020/people/jilong/steps/PUB1_GENOME/dnds/annotations/BI_Ste_All_gene.gff3
# orthogroups defined by orthofinder2
orthogroups: /faststorage/project/spider2/social_spiders_2020/people/jilong/steps/genespace/Ste_All6sp/orthofinder/Results_Sep17/Orthogroups/Orthogroups.tsv
 
# Directory for intermediary files.
working_directory_path: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/steps/hyper
# Directory for log files
log_directory_path: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/steps/hyper/logs
# Directory for helping functions and scripts
help_scripts_path: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/script/hyper/workflow_sources
# depth path
depth_path: /faststorage/project/spider2/social_spiders_2020/people/jilong/chapter3_dnm/steps/germline/BIC/filters
